name: Checks
on: pull_request
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - run: export $( cat .env.development )
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ${{env.INSTALL_CACHE_PATH}}
          key: ${{ runner.os }}-build-${{env.INSTALL_CACHE_NAME}}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{env.INSTALL_CACHE_NAME}}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm ci
  lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - run: export $( cat .env.development )
      - name: Get cached node modules
        uses: actions/cache@v2
        with:
          path: ${{env.INSTALL_CACHE_PATH}}
          key: ${{ runner.os }}-build-${{env.INSTALL_CACHE_NAME}}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{env.INSTALL_CACHE_NAME}}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Linting
        run: npm run lint:ci
  build:
    needs: [install, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - run: export $( cat .env.development )
      - name: Get cached node modules
        uses: actions/cache@v2
        with:
          path: ${{env.INSTALL_CACHE_PATH}}
          key: ${{ runner.os }}-build-${{env.INSTALL_CACHE_NAME}}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{env.INSTALL_CACHE_NAME}}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Building
        run: npm run build:prod
