name: Checks
on: pull_request
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - uses: ./.github/actions/set_environment_variables
      - run: echo $INSTALL_RESTORE_KEY
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ${{env.INSTALL_RESTORE_PATH}}
          key: ${{env.INSTALL_RESTORE_KEY}}
          restore-keys: ${{env.INSTALL_RESTORE_KEYS}}
      - run: npm i npm@6.11.3 -g && npm ci
  lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - uses: ./.github/actions/set_environment_variables
      - name: Get cached node modules
        uses: actions/cache@v2
        with:
          path: ${{env.INSTALL_RESTORE_PATH}}
          key: ${{env.INSTALL_RESTORE_KEY}}
          restore-keys: ${{env.INSTALL_RESTORE_KEYS}}
      - name: Linting
        run: npm run lint:ci
  build:
    needs: [install, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - uses: ./.github/actions/set_environment_variables
      - name: Get cached node modules
        uses: actions/cache@v2
        with:
          path: ${{env.INSTALL_RESTORE_PATH}}
          key: ${{env.INSTALL_RESTORE_KEY}}
          restore-keys: ${{env.INSTALL_RESTORE_KEYS}}
      - name: Building
        run: npm run build:prod
